'use client'

import React from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const queryClient = new QueryClient();

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <QueryClientProvider client={queryClient}>
            <html lang="en">
                <body className={inter.className}>{children}</body>
            </html>
        </QueryClientProvider>
    );
}
